//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testOmrane
{
    using System;
    using System.Collections.Generic;
    
    public partial class Affectation
    {
        public System.DateTime DateAffec { get; set; }
        public int IdMate { get; set; }
        public int IdCollab { get; set; }
    
        public virtual Collaborateur Collaborateur { get; set; }
        public virtual Materiel Materiel { get; set; }
    }
}
