//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testOmrane
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collaborateur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Collaborateur()
        {
            this.Affectations = new HashSet<Affectation>();
        }
    
        public int IdCollab { get; set; }
        public int MatriculeCollab { get; set; }
        public string NomCollab { get; set; }
        public string PrenomCollab { get; set; }
        public string Ville { get; set; }
        public int IdEntite { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Affectation> Affectations { get; set; }
        public virtual Entite Entite { get; set; }
    }
}
