//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testOmrane
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entite
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Entite()
        {
            this.Collaborateurs = new HashSet<Collaborateur>();
        }
    
        public int IdEntite { get; set; }
        public string NomEntite { get; set; }
        public string NomAgence { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Collaborateur> Collaborateurs { get; set; }
    }
}
