//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testOmrane
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materiel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materiel()
        {
            this.Affectations = new HashSet<Affectation>();
        }
    
        public int IdMate { get; set; }
        public string NumInven { get; set; }
        public string NomMate { get; set; }
        public System.DateTime DateAchat { get; set; }
        public int IDCateg { get; set; }
        public int IDMarque { get; set; }
    
        public virtual Categorie Categorie { get; set; }
        public virtual Marque Marque { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Affectation> Affectations { get; set; }
    }
}
